### PR TITLE
Enable DDR for more platforms by default

### PR DESCRIPTION
**Pull request by keithc-ca**
Now enabled for p, x and z Linux by default.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Note that configure scripts should have been regenerated after the recent merge with 9.0.4; thus the deltas are larger than might be expected.

**Comment by pshipton** [comment]
Note we want this change in jdk8.

jenkins test all all

**Comment by pshipton** [comment]
jenkins test all plinux

**Comment by pshipton** [comment]
jenkins test all plinux all

**Comment by pshipton** [comment]
jenkins test all all jdk9

**Comment by pshipton** [comment]
jenkins test all

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
jenkins test all

**Review by jdekonin — APPROVED** [review]
lgtm

**Comment by AdamBrousseau** [comment]
jenkins test all

**Comment by AdamBrousseau** [comment]
jenkins compile all

**Comment by AdamBrousseau** [comment]
jenkins test sanity

**Comment by AdamBrousseau** [comment]
jenkins compile zlinux

**Comment by keithc-ca** [comment]
It seems the build machines don't have `libdwarf-dev` installed:
```
#error "Need dwarf.h or libdwarf/dwarf.h"
```
Configuration didn't find it:
```
18:47:36 checking dwarf.h usability... no
18:47:36 checking dwarf.h presence... no
18:47:36 checking for dwarf.h... no
18:47:36 checking libdwarf/dwarf.h usability... no
18:47:36 checking libdwarf/dwarf.h presence... no
18:47:36 checking for libdwarf/dwarf.h... no
18:47:36 checking libdwarf.h usability... no
18:47:36 checking libdwarf.h presence... no
18:47:36 checking for libdwarf.h... no
18:47:36 checking libdwarf/libdwarf.h usability... no
18:47:36 checking libdwarf/libdwarf.h presence... no
18:47:36 checking for libdwarf/libdwarf.h... no
18:47:36 checking for library containing dwarf_init... no
```

**Comment by pshipton** [comment]
Created https://github.com/eclipse/openj9/issues/1506

**Comment by jdekonin** [comment]
Machines have packages installed.  Seems I don't have the ability to kick off a build though.

**Comment by pshipton** [comment]
jenkins test all zlinux,plinux

**Pull request merged**
