### PR TITLE
Remove Bits.keepAlive() and replace all calls with Reference.reachabi…

### PR DESCRIPTION
**Pull request by ben-walsh**
…lityFence()

Signed-off-by: Ben Walsh <ben_walsh@uk.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
@andrewcraik is the JIT ready for this change?

**Comment by andrew-m-leonard** [comment]
@ajcraik  is the JIT ready for this change?

**Comment by andrew-m-leonard** [comment]
bump... @andrewcraik is the JIT ready for this change?

**Comment by andrewcraik** [comment]
The JIT should be ready to go - we added that support a while ago.

**Comment by pshipton** [comment]
In another (not-public) issue I saw some performance measurements related to this change that were not favorable. There were some questions about what was being measured. The performance question should be resolved before merging this change.

**Comment by pshipton** [comment]
For the record, the performance measurements were from Hotspot and not OpenJ9.

**Comment by DanHeidinga** [comment]
> The performance question should be resolved before merging this change.

@andrew-m-leonard @pshipton Was the performance question resolved before this was merged?

**Comment by pshipton** [comment]
The performance measurements in question were from Hotspot and not OpenJ9.

**Pull request merged**
