### PR TITLE
Enable DDR by default on AIX

### PR DESCRIPTION
**Pull request by mikezhang1234567890**
Signed-off-by: mikezhang <mike.h.zhang@ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity aix depends eclipse/openj9#2939

**Comment by pshipton** [comment]
jenkins line endings check

**Comment by pshipton** [comment]
jenkins signed off by check

**Comment by pshipton** [comment]
jenkins copyright check

**Comment by mikezhang1234567890** [comment]
Not sure the copyright check will ever pass, since the non-closed `generated-config.sh` doesn't use the IBM copyright header, and that file gets the timestamp updated as part of regenerating the autoconf configs.

**Comment by pshipton** [comment]
@mikezhang1234567890 I don't expect it to pass, but in this case it didn't work properly and show the files that have incorrect copyrights.

**Comment by pshipton** [comment]
The failures seem unrelated to this change.

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
Reverting as per eclipse/openj9#3248

**Pull request merged**
