### PR TITLE
Add additional BOOT MODULE openj9.jvm

### PR DESCRIPTION
**Pull request by ben-walsh**
Fixes issue https://github.com/eclipse/openj9/issues/108

### CODE REVIEW

**Comment by ben-walsh** [comment]
Personal build in progress - https://urv-jenkins.canlab.ibm.com:9095/view/OpenJ9/job/openj9.personal/44

**Comment by ben-walsh** [comment]
Further personal build in progress following re-position from 1st to 2nd - https://urv-jenkins.canlab.ibm.com:9095/view/OpenJ9/job/openj9.personal/45

**Comment by ben-walsh** [comment]
Both personal builds look to be successful and local build was successful.

**Comment by jdekonin** [comment]
Does it fix the issue it was raised against?  Is there an automated test for that? And should that be included as a sanity/tier1 test of some sort?

**Pull request merged**
