### PR TITLE
Perform a check to verify freemarker.jar exists where user specifies

### LINKED ISSUE #24: If there's no freemarker.jar, configure should fail.
If you omit the '--with-freemarker-jar' command-line option, configure complains.

If you include the option and the jar file is not there, or if you provide a path that does not contain the freemarker jar file, configure doesn't complain and there is a cryptic failure during the compile.

### PR DESCRIPTION
**Pull request by jdekonin**
Fixes #24

Signed-off-by: Joe Dekoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
Output from no freemarker.jar option passed
>>>
checking that freemarker location is set...
The FreeMarker library is required to build the OpenJ9 build tools
and has to be provided during configure process.
Download the FreeMarker library and unpack it into an arbitrary directory:
wget https://sourceforge.net/projects/freemarker/files/freemarker/2.3.8/freemarker-2.3.8.tar.gz/download -O freemarker-2.3.8.tar.gz
tar -xzf freemarker-2.3.8.tar.gz
Then run configure with '--with-freemarker-jar=<freemarker_jar>'
configure: Could not find freemarker.jar
configure: error: Cannot continue
configure exiting with result code 1
>>>

Output from freemarker option passed but jar doesn't exist
>>>
checking that freemarker location is set... yes
checking for freemarker.jar... no
configure: error: freemarker.jar not found in directory indicated
configure exiting with result code 1
>>>

Output from a valid freemarker option passed to configure
>>>
checking that freemarker location is set... yes
checking for /home/openj9/freemarker.jar... yes
>>>

**Comment by andrew-m-leonard** [comment]
@jdekonin Joe, do you know why the closed/autoconf/generated-configure.sh change is so large?

**Comment by jdekonin** [comment]
Its not much bigger than common/autoconf/generated-configure.sh.  In fact, the difference is only the addons that are in the closed directory.  common/autoconf/autogen.sh appears to make a complete copy plus closed content in closed/autoconf/generated-configure.sh, it isn't just generated content from closed.

**Comment by jdekonin** [comment]
@keithc-ca, this is the pr I was mentioning about freemarker checks.  It isn't the same as the issue of assuming a default location (and check) if the option isn't specified but I believe this is a step in that direction.

**Comment by keithc-ca** [comment]
It looks like was stale prior to this PR. @jdekonin Is that your understanding?

**Comment by jdekonin** [comment]
I see the difference more so since #16 was merged.  I'm going to try a rebase and re-run the autogen script although I don't see why it didn't add the copyright content back in #16??

**Comment by jdekonin** [comment]
The freemarker changes I added are in the closed/../generated-configure.sh, but it seems to add the copyright and a bunch of freetype changes in there as well.  Not sure why that wouldn't have been there previously when it should have been.

**Pull request merged**
