### PR TITLE
Export CMake variables

### PR DESCRIPTION
**Pull request by dnakamura**
Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
@dnakamura Can you expand on why these variables need to be exported?

**Comment by DanHeidinga** [comment]
jdk10 version of this change: https://github.com/ibmruntimes/openj9-openjdk-jdk10/pull/34

**Comment by dnakamura** [comment]
Variables need to be exported due to the simplifications from #154 . In a nutshell previously we had `OPENJ9_ENABLE_CMAKE` in the openjdk build files and `ENABLE_CMAKE` in the openj9 makefiles.  If `OPENJ9_ENABLE_CMAKE` was true it would append `ENABLE_CMAKE=true` to the command when calling `buildtools.mk`. With #154  (and eclipse/openj9#1907) We move to a simpler model of just using `OPENJ9_ENABLE_CMAKE` everywhere. However since we no longer explicitly set it on the command line when calling buildtools.mk,  we need to export `OPENJ9_ENABLE_CMAKE` so that it will be picked up there

**Review by DanHeidinga — APPROVED** [review]
lgtm

**Pull request merged**
