### PR TITLE
Remove references to libffi shared libary

### PR DESCRIPTION
**Pull request by gacholio**
The library is no longer used/required by OpenJ9.

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
jenkins test sanity plinux jdk9

**Review by DanHeidinga — APPROVED** [review]
lgtm

**Comment by gacholio** [comment]
sanity build stuck

**Comment by gacholio** [comment]
jenkins test sanity plinux jdk9

**Review by pshipton — APPROVED** [review]

**Pull request merged**
